-- Baseline schema, taken from the former schema-tables.sql, schema-functions.sql and
-- schema-triggers.sql (which ran on every start via spring.sql.init and began with DROP TABLE).

-- Create Tables
CREATE TABLE users (
    email VARCHAR(255) NOT NULL,
    phone BIGINT,
    name VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (email)
);

CREATE TABLE student (
    email VARCHAR(255) NOT NULL,
    regno BIGINT UNIQUE,
    PRIMARY KEY (email),
    CONSTRAINT FKSE FOREIGN KEY (email) REFERENCES users(email)
);

CREATE TABLE professor (
    email VARCHAR(255) NOT NULL,
    is_cultural BOOLEAN,
    PRIMARY KEY (email),
    CONSTRAINT FKPE FOREIGN KEY (email) REFERENCES users(email)
);

CREATE TABLE floor_manager (
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (email),
    CONSTRAINT FKFME FOREIGN KEY (email) REFERENCES users(email)
);

CREATE TABLE security (
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (email),
    CONSTRAINT FKSEE FOREIGN KEY (email) REFERENCES users(email)
);

CREATE TABLE student_council (
    email VARCHAR(255) NOT NULL,
    position VARCHAR(255),
    -- Note: regno is inherited from student, no need to redefine column here
    PRIMARY KEY (email),
    -- Constraint links StudentCouncil to Student (which links to Users)
    CONSTRAINT FKSCSE FOREIGN KEY (email) REFERENCES student(email)
);

CREATE TABLE room (
    block VARCHAR(255) NOT NULL,
    room VARCHAR(255) NOT NULL, -- Matches Room.java @Column(name="room")
    manager_email VARCHAR(255),
    PRIMARY KEY (block, room),
    CONSTRAINT FKRME FOREIGN KEY (manager_email) REFERENCES floor_manager(email)
);

CREATE TABLE club (
    name VARCHAR(255) NOT NULL,
    faculty_head_email VARCHAR(255) UNIQUE,
    poc_student_email VARCHAR(255) UNIQUE,
    PRIMARY KEY (name),
    CONSTRAINT FKFHE FOREIGN KEY (faculty_head_email) REFERENCES professor(email),
    CONSTRAINT FKPSE FOREIGN KEY (poc_student_email) REFERENCES student(email)
);

CREATE TABLE club_membership (
    club_name VARCHAR(255) NOT NULL,
    stu_email VARCHAR(255) NOT NULL,
    PRIMARY KEY (club_name, stu_email),
    CONSTRAINT FKCNC FOREIGN KEY (club_name) REFERENCES club(name),
    CONSTRAINT FKCMSE FOREIGN KEY (stu_email) REFERENCES student(email)
);

CREATE TABLE booking (
    start_time TIMESTAMP(6) NOT NULL,
    block VARCHAR(255) NOT NULL,
    room_no VARCHAR(255) NOT NULL, -- Matches Booking.java @Column(name="room_no")
    end_time TIMESTAMP(6) NOT NULL,
    club_name VARCHAR(255),
    overall_status VARCHAR(255) CHECK (overall_status IN ('PENDING_APPROVAL','APPROVED','REJECTED','CANCELLED')),
    purpose VARCHAR(255),
    student_email VARCHAR(255),
    PRIMARY KEY (start_time, block, room_no),
    CONSTRAINT FKBCN FOREIGN KEY (club_name) REFERENCES club(name),
    -- References room table using its composite key (block, room) but matches booking columns (block, room_no)
    CONSTRAINT FKBR FOREIGN KEY (block, room_no) REFERENCES room(block, room),
    CONSTRAINT FKBSE FOREIGN KEY (student_email) REFERENCES student(email)
);

CREATE TABLE booking_approval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    approval_time TIMESTAMP(6),
    start_time TIMESTAMP(6),
    approval_status VARCHAR(255) CHECK (approval_status IN ('PENDING','APPROVED','REJECTED')),
    approver_email VARCHAR(255),
    approver_role VARCHAR(255) CHECK (approver_role IN ('FACULTY_HEAD','STUDENT_COUNCIL','CULTURAL_PROF','FLOOR_MANAGER','SECURITY')),
    block VARCHAR(255),
    comments VARCHAR(255),
    room_no VARCHAR(255),
    PRIMARY KEY (id),
    -- Composite Foreign Key referencing booking's composite primary key
    CONSTRAINT FKBAB FOREIGN KEY (start_time, block, room_no) REFERENCES booking(start_time, block, room_no)
);


-- Not-null check functions

CREATE OR REPLACE FUNCTION check_booking_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  -- Check essential fields derived from the composite primary key and relationships
  IF NEW.block IS NULL THEN
    RAISE EXCEPTION 'Booking cannot be inserted: "block" cannot be NULL.';
  END IF;
  IF NEW.room_no IS NULL THEN
    RAISE EXCEPTION 'Booking cannot be inserted: "room_no" cannot be NULL.';
  END IF;
  IF NEW.start_time IS NULL THEN
    RAISE EXCEPTION 'Booking cannot be inserted: "start_time" cannot be NULL.';
  END IF;

  -- Check other logically required fields for a valid initial booking request
  IF NEW.end_time IS NULL THEN
    RAISE EXCEPTION 'Booking cannot be inserted: "end_time" cannot be NULL.';
  END IF;
  IF NEW.purpose IS NULL THEN
    RAISE EXCEPTION 'Booking cannot be inserted: "purpose" cannot be NULL.';
  END IF;
  IF NEW.student_email IS NULL THEN
    RAISE EXCEPTION 'Booking cannot be inserted: "student_email" cannot be NULL.';
  END IF;
  IF NEW.club_name IS NULL THEN
    RAISE EXCEPTION 'Booking cannot be inserted: "club_name" cannot be NULL';
  END IF;
  -- Note: overall_status is usually set by the application logic/default, not checked on initial insert.

  -- If all checks pass, allow the insertion
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_approval_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  -- Check Foreign Key components referencing the booking
  IF NEW.block IS NULL THEN
    RAISE EXCEPTION 'Booking Approval cannot be inserted: "block" cannot be NULL.'; 
  END IF;
  IF NEW.room_no IS NULL THEN
    RAISE EXCEPTION 'Booking Approval cannot be inserted: "room_no" cannot be NULL.'; 
  END IF;
  IF NEW.start_time IS NULL THEN
    RAISE EXCEPTION 'Booking Approval cannot be inserted: "start_time" cannot be NULL.'; 
  END IF;

  -- Check essential approval details
  IF NEW.approver_email IS NULL THEN
    RAISE EXCEPTION 'Booking Approval cannot be inserted: "approver_email" cannot be NULL.'; 
  END IF;
  IF NEW.approver_role IS NULL THEN
    RAISE EXCEPTION 'Booking Approval cannot be inserted: "approver_role" cannot be NULL.'; 
  END IF;
  IF NEW.approval_status IS NULL THEN
    RAISE EXCEPTION 'Booking Approval cannot be inserted: "approval_status" cannot be NULL.'; 
  END IF;
  IF NEW.approval_time IS NULL THEN
    RAISE EXCEPTION 'Booking Approval cannot be inserted: "approval_time" cannot be NULL.'; 
  END IF;

  -- Comments are optional, so not checked here.
  -- ID is auto-generated, not checked in BEFORE INSERT.
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_club_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.name IS NULL THEN
    RAISE EXCEPTION 'Club cannot be inserted: "name" cannot be NULL.'; 
  END IF;
  IF NEW.poc_student_email IS NULL THEN
    RAISE EXCEPTION 'Club cannot be inserted: "poc_student_email" cannot be NULL.'; 
  END IF;
  IF NEW.faculty_head_email IS NULL THEN
    RAISE EXCEPTION 'Club cannot be inserted: "faculty_head_email" cannot be NULL.'; 
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_membership_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.club_name IS NULL THEN
    RAISE EXCEPTION 'Club Membership cannot be inserted: "club_name" cannot be NULL.';
  END IF;
  IF NEW.stu_email IS NULL THEN
    RAISE EXCEPTION 'Club Membership cannot be inserted: "stu_email" cannot be NULL.'; 
  END IF;

  RETURN NEW; 
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_user_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.name IS NULL THEN
    RAISE EXCEPTION 'User cannot be inserted: "name" cannot be NULL.';
  END IF;
  IF NEW.email IS NULL THEN
    RAISE EXCEPTION 'User cannot be inserted: "email" cannot be NULL.'; 
  END IF;
  IF NEW.password IS NULL THEN
    RAISE EXCEPTION 'User cannot be inserted: "password" cannot be NULL.'; 
  END IF;
  -- phone nullables shouldn't matter all that much

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_professor_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.email IS NULL THEN
    RAISE EXCEPTION 'Professor cannot be inserted: "email" cannot be NULL.'; 
  END IF;
  IF NEW.is_cultural IS NULL THEN
    RAISE EXCEPTION 'Professor cannot be inserted: "is_cultural" cannot be NULL.';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_security_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.email IS NULL THEN
    RAISE EXCEPTION 'Security personnel cannot be inserted: "email" cannot be NULL.'; 
  END IF;

  RETURN NEW; 
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION check_student_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.email IS NULL THEN
    RAISE EXCEPTION 'Student cannot be inserted: "email" cannot be NULL.'; 
  END IF;
  IF NEW.regno IS NULL THEN
    RAISE EXCEPTION 'Student cannot be inserted: "regno" cannot be NULL.'; 
  END IF;

  RETURN NEW; 
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_student_council_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.email IS NULL THEN
    RAISE EXCEPTION 'Student Council member cannot be inserted: "email" cannot be NULL.';
  END IF;
  IF NEW.position IS NULL THEN
    RAISE EXCEPTION 'Student Council member cannot be inserted: "position" cannot be NULL.';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_floor_manager_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.email IS NULL THEN
    RAISE EXCEPTION 'Floor manager cannot be inserted: "email" cannot be NULL.'; 
  END IF;

  RETURN NEW; 
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION check_room_not_null_fields()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.block IS NULL THEN
    RAISE EXCEPTION 'Room cannot be inserted: "block" cannot be NULL.';
  END IF;
  IF NEW.room IS NULL THEN
    RAISE EXCEPTION 'Room cannot be inserted: "room" (number/name) cannot be NULL.';
  END IF;
  IF NEW.manager_email IS NULL THEN
    RAISE EXCEPTION 'Room cannot be inserted: "manager_email" cannot be NULL.';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- Not-null check triggers

CREATE TRIGGER trg_check_booking_not_null
BEFORE INSERT ON booking
FOR EACH ROW
EXECUTE FUNCTION check_booking_not_null_fields();

CREATE TRIGGER trg_check_approval_not_null
BEFORE INSERT ON booking_approval
FOR EACH ROW
EXECUTE FUNCTION check_approval_not_null_fields();

CREATE TRIGGER trg_check_club_not_null
BEFORE INSERT ON club
FOR EACH ROW
EXECUTE FUNCTION check_club_not_null_fields();

CREATE TRIGGER trg_check_membership_not_null
BEFORE INSERT ON club_membership
FOR EACH ROW
EXECUTE FUNCTION check_membership_not_null_fields();

CREATE TRIGGER trg_check_user_not_null
BEFORE INSERT ON users
FOR EACH ROW
EXECUTE FUNCTION check_user_not_null_fields();

CREATE TRIGGER trg_check_professor_not_null
BEFORE INSERT ON professor
FOR EACH ROW
EXECUTE FUNCTION check_professor_not_null_fields();

CREATE TRIGGER trg_check_security_not_null
BEFORE INSERT ON security
FOR EACH ROW
EXECUTE FUNCTION check_security_not_null_fields();

CREATE TRIGGER trg_check_student_not_null
BEFORE INSERT ON student
FOR EACH ROW
EXECUTE FUNCTION check_student_not_null_fields();

CREATE TRIGGER trg_check_student_council_not_null
BEFORE INSERT ON student_council
FOR EACH ROW
EXECUTE FUNCTION check_student_council_not_null_fields();

CREATE TRIGGER trg_check_floor_manager_not_null
BEFORE INSERT ON floor_manager
FOR EACH ROW
EXECUTE FUNCTION check_floor_manager_not_null_fields();

CREATE TRIGGER trg_check_room_not_null
BEFORE INSERT ON room
FOR EACH ROW
EXECUTE FUNCTION check_room_not_null_fields();
